language: go

go:
  - 1.11.x

# set tag for helm chart
env:
  global:
    - HELM_URL=https://storage.googleapis.com/kubernetes-helm/helm-v2.11.0-linux-amd64.tar.gz

before_install:
   - go get -u github.com/golang/dep/cmd/dep
   - make dep-vendor

install:
  - go get github.com/alecthomas/gometalinter
  # - go get github.com/GoASTScanner/gas/cmd/gas/...
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

before_script:
  - gometalinter --install --update

script:
  # Execute static checks
  - gometalinter --vendor ./...

  # Execute tests and generate coverage for all the packages except fakes and tests
  - make test
  - goveralls -coverprofile profile.cov -service=travis-ci

  # Execute security scan
  # - gas ./...

before_deploy:
  # Change branch
  - git checkout -b ${TRAVIS_TAG:-master}

  # Download and install helm
  - wget ${HELM_URL} -O helm.tar.gz
  - tar -xzf helm.tar.gz
  - mv linux-amd64/helm $HOME/bin
  - rm -rf helm.tar.gz linux-amd64

  # Change default docker image tag in values.yaml
  - "sed -i -e 's/tag: master/tag: '${TRAVIS_TAG:-master}'/g' ./charts/service-broker-proxy-k8s/values.yaml"

  # Create helm-chart
  - mkdir out
  - helm package --app-version ${TRAVIS_TAG:-"master"} -d ./out charts/service-broker-proxy-k8s --save=false

  # Commit version change before deploy
  - git add charts/service-broker-proxy-k8s
  - git commit -m "version ${TRAVIS_TAG:-master}"

deploy:
  provider: releases
  file_glob: true
  file: out/*
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  on:
    tags: true

notifications:
  slack: openservicebrokerapi:KQo2QAC6LXeEeXPOemOXja48
