# Default values for service-broker-proxy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: quay.io/service-manager/sb-proxy-k8s
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

file:
  name: application
  location: /etc/config
  format: yml

sm:
  user: admin
  password: admin

# Credentials used to register the proxy as a broker
reg:
  user: admin
  password: admin

config:
  server:
    port: 8081
    logLevel: debug
    logFormat: text
    timeout: 5000ms
    ResyncPeriod: 10s
  sm:
    host: http://service-manager.local.pcfdev.io
    osbApi: /v1/osb
    requestTimeout: 6000ms
  k8s:
    client:
      httpClient:
        timeout: 6000ms
